<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Services\Qlib;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $payload = [
            'data' => [
                [
                    'id' => '019be6ab-42b8-73f4-a900-bbef2fcb6a62',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Douglas Alvares',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'douglas.alvares@gmail.com',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 3,
                    'config' => [
                        'nome_fantasia' => '',
                        'celular' => '',
                        'telefone_residencial' => '',
                        'telefone_comercial' => '',
                        'rg' => '',
                        'nascimento' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019be1de-b7a4-71ad-b2b6-8ee58c11d972',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => 4,
                    'client_permission' => [],
                ],
                [
                    'id' => '019be680-0925-7327-87a3-8675cf4d6b87',
                    'tipo_pessoa' => 'pf',
                    'name' => 'João Carlos Ribeiro da Silva Junior',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'joao.ribeiro@mileto.tec.br',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 3,
                    'config' => [
                        'nome_fantasia' => '',
                        'celular' => '',
                        'telefone_residencial' => '',
                        'telefone_comercial' => '',
                        'rg' => '',
                        'nascimento' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019be1de-b7a4-71ad-b2b6-8ee58c11d972',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => 3,
                    'client_permission' => [],
                ],
                [
                    'id' => '019be67e-11b9-7027-9570-5244edeeea75',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Thauany Mileny da Silva Batista',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'contato@yellowbc.com.br',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 3,
                    'config' => [
                        'nome_fantasia' => '',
                        'celular' => '',
                        'telefone_residencial' => '',
                        'telefone_comercial' => '',
                        'rg' => '',
                        'nascimento' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019be1de-b7a4-71ad-b2b6-8ee58c11d972',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => 1,
                    'client_permission' => [],
                ],
                [
                    'id' => '019be201-0013-71c4-9de3-a5e7633191ec',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Vendedor MedGo',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'vendasmedgo@gmail.com',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 5,
                    'config' => [
                        'nome_fantasia' => '',
                        'celular' => '',
                        'telefone_residencial' => '',
                        'telefone_comercial' => '',
                        'rg' => '',
                        'nascimento' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019be115-b5a3-709d-a443-c46778a9e1b8',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => 2,
                    'client_permission' => [],
                ],
                [
                    'id' => '019be1de-b7a4-71ad-b2b6-8ee58c11d972',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Luciano Brandão Baptista',
                    'razao' => '',
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'yellowbcompany@gmail.com',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'm',
                    'verificado' => 'n',
                    'permission_id' => 2,
                    'config' => [
                        'celular' => '',
                        'telefone_comercial' => '',
                        'nascimento' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                        'nome_fantasia' => '',
                        'telefone_residencial' => '',
                        'rg' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019be115-b5a3-709d-a443-c46778a9e1b8',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => 1,
                    'client_permission' => [10],
                ],
                [
                    'id' => '019be115-b5a3-709d-a443-c46778a9e1b8',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Welligton Santos',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'mastertechjf@gmail.com',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 1,
                    'config' => [
                        'nome_fantasia' => '',
                        'celular' => '',
                        'telefone_residencial' => '',
                        'telefone_comercial' => '',
                        'rg' => '',
                        'nascimento' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019bd8df-b9bb-7300-9434-de90617c7032',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => 1,
                    'client_permission' => [],
                ],
                [
                    'id' => '019bd8df-bd23-71f9-85f1-23f1bcb16a70',
                    'tipo_pessoa' => 'pj',
                    'name' => 'IZA Seguradora S.A.',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => '40.004.544/0001-46',
                    'email' => 'contato@iza.com.br',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 's',
                    'permission_id' => 6,
                    'config' => [
                        'cod_susep' => '0457-0',
                        'registro_susep' => [
                            '15414.619412/2020-85 (Produto Acidente Pessoal)',
                            '15414.644857/2024-27 (Produto Seguro Viagem)',
                            '15414.616755/2025-01 (Produto Vida em Grupo Taxa Média)',
                            '15414.617802/2025-25 (Acidente Pessoal Coletivo)',
                        ],
                        'autorizacao' => 'Autorizada pela Susep a atuar como seguradora independente',
                        'tag' => 'IZA',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => null,
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => null,
                    'client_permission' => null,
                ],
                [
                    'id' => '019bd8df-bd29-734a-ab03-c758fc7ffddb',
                    'tipo_pessoa' => 'pj',
                    'name' => 'Sul América Seguros de Pessoas e Previdência S.A.',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => '01.704.513/0001-46',
                    'email' => 'contato@sulamerica.com.br',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 's',
                    'permission_id' => 6,
                    'config' => [
                        'sac' => '0800 722 0504',
                        'sac_deficiencia' => 'Pessoas com Deficiência Auditiva e na Fala - 24H',
                        'whatsapp' => '(11) 3004-9723',
                        'tag' => 'SulAmerica',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => null,
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => null,
                    'client_permission' => null,
                ],
                [
                    'id' => '019bd8df-b9bb-7300-9434-de90617c7032',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Fernando Queta',
                    'razao' => null,
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'fernando@maisaqui.com.br',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 1,
                    'config' => null,
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => null,
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => null,
                    'client_permission' => null,
                ],
                [
                    'id' => '019bd8df-b9c8-734b-92d9-99a3612aa6e9',
                    'tipo_pessoa' => 'pf',
                    'name' => 'Developer',
                    'razao' => '',
                    'cpf' => null,
                    'cnpj' => null,
                    'email' => 'fernando@mastertechbr.com',
                    'celular' => null,
                    'email_verified_at' => null,
                    'status' => 'actived',
                    'genero' => 'ni',
                    'verificado' => 'n',
                    'permission_id' => 1,
                    'config' => [
                        'celular' => '',
                        'telefone_comercial' => '',
                        'nascimento' => '',
                        'cep' => '',
                        'endereco' => '',
                        'numero' => '',
                        'complemento' => '',
                        'bairro' => '',
                        'cidade' => '',
                        'uf' => '',
                        'nome_fantasia' => '',
                        'telefone_residencial' => '',
                        'rg' => '',
                        'escolaridade' => '',
                        'profissao' => '',
                        'tipo_pj' => '',
                    ],
                    'preferencias' => null,
                    'foto_perfil' => null,
                    'ativo' => 's',
                    'autor' => '019bd8df-b9c8-734b-92d9-99a3612aa6e9',
                    'excluido' => 'n',
                    'reg_excluido' => null,
                    'deletado' => 'n',
                    'reg_deletado' => null,
                    'organization_id' => null,
                    'client_permission' => [],
                ],
            ],
        ];

        $tableName = (new User())->getTable();

        foreach ($payload['data'] as $userData) {
            if (!isset($userData['password'])) {
                $userData['password'] = Hash::make('password');
            }
            // Filter fields that exist in the table
            $validData = array_filter($userData, function ($key) use ($tableName) {
                return \Illuminate\Support\Facades\Schema::hasColumn($tableName, $key);
            }, ARRAY_FILTER_USE_KEY);

            User::updateOrCreate(
                ['email' => $userData['email']],
                $validData
            );
        }
    }
}
